language: python
python: 
  - "3.6"
before_install:
  - pip install -U pytest 
  - pip install pytest-cov
  - pip install -U codecov
install:
  - pip install autodiff32
script:
  - echo "skipping tests"
after_success:
  - codecov

